### ISSUE TITLE
ncWMS-2.2.1 and ncWMS-2.2.2 dataset load bug

### ISSUE THREAD

**Issue by aj0415** [Reading-eScience-Centre/ncwms#1]
When adding a dataset through the admin page the status says 'Loading' but nothing happens and no logs are written to. Any ideas to what may be causing this? There are no errors displayed on the status page for the dataset under the Error report. It only says 'Starting loading' and ' This dataset does not contain any errors so far'. We are currently using the 2.0 version and there are no issues with that version.

**Comment by guygriffiths** [comment]
Have you got a dataset you could share that has this issue?  Ideally something small, but whatever you have would be very useful.  Or if it's a publicly-accessible remote dataset, just the URL will be fine.

**Comment by aj0415** [comment]
Its for all of our datasets. They all currently work in the 2.0 version. Here is one of the datasets: https://opendap.larc.nasa.gov/opendap/.GIBS/MOPITT/MOP03JM.006/MOP03JM.006.ncml.html

**Comment by guygriffiths** [comment]
How are you accessing this dataset (i.e. what are you putting in the `location` box in the admin interface)?  I downloaded the dataset and added it from my local disk - it loaded in <2s, but there is no guarantee that the downloaded data is identical to your source data (since OPeNDAP is writing out new data).

**Comment by aj0415** [comment]
I am replacing https://opendap.larc.nasa.gov/ with http://localhost:8080/ and the rest of the path is the same.

**Comment by guygriffiths** [comment]
So which of these are you using?  This:
http://localhost:8080/opendap/.GIBS/MOPITT/MOP03JM.006/MOP03JM.006.ncml.html
or this:
http://localhost:8080/opendap/.GIBS/MOPITT/MOP03JM.006/MOP03JM.006.ncml

The first one will never work, because it is a link to the HTML description of the data, but it should at least fail with an error.  The second one should work fine.

This has highlighted a bug in ncWMS whereby `https://` is not recognised as being a remote location, but when I fix that, I have no issues with loading a dataset with the location:
https://opendap.larc.nasa.gov/opendap/.GIBS/MOPITT/MOP03JM.006/MOP03JM.006.ncml

It's a little slow (which is to be expected with remote datasets), but it works fine using v2.2.2 + HTTPS fix.  Can you give me any other information about the issue?

**Comment by aj0415** [comment]
I am using the http://localhost:8080/opendap/.GIBS/MOPITT/MOP03JM.006/MOP03JM.006.ncml. Unfortunately there is not much more info I can give you because no logs are being written. I used the same exact configurations and location that worked on the previous versions of ncWMS and it says the status of the dataset is loading but that all that happens and it stays like that forever and never loads or performs any action and no error comes up.

**Comment by guygriffiths** [comment]
I have uploaded a version of ncWMS here:
http://www.personal.rdg.ac.uk/~qx901922/ncWMS2.war
This should work with HTTPS remote locations.  Could you please try this version with both:
http://localhost:8080/opendap/.GIBS/MOPITT/MOP03JM.006/MOP03JM.006.ncml
and:
https://opendap.larc.nasa.gov/opendap/.GIBS/MOPITT/MOP03JM.006/MOP03JM.006.ncml
and let me know the results?  Perhaps this is an issue with having a local opendap server...

**Comment by aj0415** [comment]
I was able to get the new version you sent me to work.

**Comment by guygriffiths** [comment]
OK, good to hear it, thanks for letting us know :)
