### ISSUE TITLE
Differences From ncWMS1x

### ISSUE THREAD

**Issue by acrosby** [Reading-eScience-Centre/ncwms#10]
Is it possible to configure vector marker density like it was in version 1? Similarly, is it possible to configure contours (perhaps via sld?) so that they are smooth rather than explicitly following the gridpoints at the data resolution as seemed to be happening in version 1? (The later is particularly messy in contouring unstructured meshes.)

Should these be EDAL issues?

Thanks,
Alex

@kwilcox , since i was asking him about it earlier

**Comment by guygriffiths** [comment]
@acrosby - It is possible to configure the vector marker size via SLD.  See https://github.com/Reading-eScience-Centre/edal-java/blob/master/graphics/src/main/resources/styles/arrows.xml for an example.  The <resc:ArrowSize> tag defines the arrow size in pixels.  The density is calculated from that, such that the vector markers will tile without overlapping or large gaps, and no two arrows will touch one another.

It is not possible to draw smooth contours.  The way the code architecture works, the drawing code receives the data at the required resolution (i.e. blocky if zoomed in), rather than receiving the underlying data and then doing the nearest-neighbour matching itself.  This does mean that contours look jagged when zoomed in, but although ugly, it's an accurate representation of the underlying data.

These are both EDAL issues, but it's fine to report them here.

**Comment by guygriffiths** [comment]
Closing, since it's been moved to https://github.com/Reading-eScience-Centre/edal-java/issues/12
