### ISSUE TITLE
Problem parsing parameters

### ISSUE THREAD

**Issue by cornelius-agrippa** [Reading-eScience-Centre/ncwms#12]
Hello,

I've updated a version 1 ncWMS container to version 2.

However when I try to make the following request:
`/ncWMS/wms?item=minmax&layers=region_302/bat&bbox=-8.674641491,41.13761336,-8.577441491,41.14801336&elevation=0&time=0&srs=CRS:84&width=256&height=256&request=GetMetadata`

I get the error:
```
<ServiceExceptionReport version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
  <ServiceException>
      Problem parsing parameters
  </ServiceException>
</ServiceExceptionReport>
```

The log file says the same thing:
`Wms Exception caught: "Problem parsing parameters" from:uk.ac.rdg.resc.edal.wms.WmsServlet:1689`

The layer works in godiva, and it's also available if I query it like:
`/ncWMS/wms?request=GetMetadata&item=layerDetails&layerName=region_302` 

If I revert to version 1 it also works fine. 

Did any parameters change in version 2? I'm probably passing something that I shouldn't, but I'm not seeing what.

Sorry if this is a silly question, I'm quite new to ncWMS.

Best regards.

**Comment by guygriffiths** [comment]
I suspect that the problem is that your time parameter is not in ISO8601 format.  I think I need to make the error messages more explicit though - "Problem parsing parameters" isn't very helpful...

**Comment by guygriffiths** [comment]
OK, I've looked into it in a little more detail, and the problems are:
* The time could be wrong.  ncWMS will interpret `time=0` as `0000-01-01T00:00:00.000Z` which may or may not be part of your time domain
* You need a `VERSION=1.1.1` parameter to specify which version of WMS you are using.  You can use `VERSION=1.3.0` but then you will need to change the `SRS` parameter to `CRS`.  Requiring this is possibly overkill, but it does help define how to specify the coordinate reference system.
* You need to specify the `STYLES` parameter.  Set it to `default-scalar`.  This is a bug, it shouldn't be required.  I've fixed it in my development version, so it'll make the next release.

**Comment by cornelius-agrippa** [comment]
Hello, 

Specifying version `1.3.0` and `CRS` instead of `SRS` did it (I should have read the WMS standard :blush: better). Thank you for teaching me today!

Indeed it did ask for a style. After the fix what style will it use by default? Whatever is specified in the dataset in the ncWMS Admin page? Or will it use `default-scalar`?

Also for reference sakes, here's the final query that worked:
`/ncWMS/wms?request=GetMetadata&version=1.3.0&styles=default-scalar&layers=region_302/bat&item=minmax&elevation=0&time=0&crs=CRS:84&width=256&height=256&bbox=-8.674641491,41.13761336,-8.577441491,41.14801336`

Thank you for your quick reply

Best regards

**Comment by guygriffiths** [comment]
Great, glad it worked.  When calculating the min/max for a layer the style is generally not important.  For scalar layers any supported style will give the same result.  If none is specified, it will use the default style for that layer (i.e. default-scalar).

**More detail - feel free to ignore:**

However, where it becomes important is when you have grouped variables and you are plotting the parent of the group.  In that case, the field which you want the min/max for can potentially vary (although in reality I don't believe that we have any cases where it does).

As an example, when ncWMS detects vector component fields, it groups them together with dynamically generated magnitude and direction fields under a parent vector layer.  Plotting the parent layer displays both magnitude (by colour) and direction (by arrows) together.  At which point getting the min/max becomes more complex since there are two fields.  The style `default-vector` defines the fact that when a call to get min/max is made, it is the range of the _magnitude_ which should be returned (since min/max is generally used for setting the colour scale).  However, the design is flexible enough that another style could be defined for vector layers which required the direction to be scaled, in which case retrieving min/max while specifying that style would return the range of the direction field.  In practice this is unlikely to happen for vectors, but I've kept it open-ended in case it becomes important for future grouped fields.
