### ISSUE TITLE
Undocumented behaviour for GetMetadata item=minmax

### ISSUE THREAD

**Issue by NJRBailey** [Reading-eScience-Centre/ncwms#29]
Hi, we're facing a bit of confusion over how the *minmax* item should be used in a **GetMetadata** request. This behaviour isn't documented under [GetMetadata](https://reading-escience-centre.gitbooks.io/ncwms-user-guide/content/04-usage.html#getmetadata) so we have no reference as to how we should correctly use it. We are trying to achieve the following usage:

### What we are doing
We want to get the minimum data value and the maximum data value for the entirety of the data in order to automatically get minimum and maximum scale values. We would expect to send a request in the following format:
`[baseurl]?request=GetMetadata&item=minmax&layers=[id]&bbox=-180,-90,180,90&time=[datetime]`
but we actually have to include projection, width and height parameters as well, so our requests look like this:
`[baseurl]?request=GetMetadata&item=minmax&layers=[id]&bbox=-180,-90,180,90&time=[datetime]&srs=EPSG:4326&width=[width]&height=[height]`

### What we expect to happen
We expect that the min and max always return the same based on the layer id, the bbox and the time.

### What is happening
When the width, height or projection are changed, the returned min and max values are quite a lot different. I have attached some example requests below:

- Width/height = **1** returns **0.49, 0.49** [request](https://rsg.pml.ac.uk/thredds/wms/CCI_ALL-v3.1-5DAY?request=GetMetadata&item=minmax&layers=chlor_a&bbox=-180,-90,180,90&srs=EPSG:4326&width=1&height=1&time=2001-07-05T00:00:00.000Z)
- Width/height = **10** returns **0.08, 2.03** [request]( https://rsg.pml.ac.uk/thredds/wms/CCI_ALL-v3.1-5DAY?request=GetMetadata&item=minmax&layers=chlor_a&bbox=-180,-90,180,90&srs=EPSG:4326&width=10&height=10&time=2001-07-05T00:00:00.000Z)
- Width/height = **100** returns **0.02, 24.8** [request](https://rsg.pml.ac.uk/thredds/wms/CCI_ALL-v3.1-5DAY?request=GetMetadata&item=minmax&layers=chlor_a&bbox=-180,-90,180,90&srs=EPSG:4326&width=100&height=100&time=2001-07-05T00:00:00.000Z)
- Width/height = **1000** returns **0.01, 63.1** [request]( https://rsg.pml.ac.uk/thredds/wms/CCI_ALL-v3.1-5DAY?request=GetMetadata&item=minmax&layers=chlor_a&bbox=-180,-90,180,90&srs=EPSG:4326&width=1000&height=1000&time=2001-07-05T00:00:00.000Z)

Bear in mind that the bbox here is always set to be global, so we would not expect any variation from the min and max values across the whole world.

**Comment by guygriffiths** [comment]
The minmax request extracts the data on the given area at the supplied resolution and returns the minimum and maximum values in that area. Since the underlying data may be very high resolution, extracting every value from it could be too time-consuming (particularly for remote data). It's main purpose is for quickly seeing the colour scale within Godiva3.

For example, if you set the width and height to 1, only a single value (at the centre of your bounding box) would be extracted. When estimating the value range initially, I think we use a 100x100 box and add a small margin to the limits. This will miss small regions with extreme values (as the difference between your 100 and your 1000 examples shows) but is generally good enough for a first approximation.

I hope that explains how it works. I'd be happy to make some changes to it to get a more accurate measurement, particularly if you have a specific use case.

**Comment by NJRBailey** [comment]
Thanks for the quick response - I don't think there's any need to make changes to the way that works, but thanks for the offer :) Our use case is basically the same as the use case you mentioned for Godiva3. We just wanted to understand what the width and height parameters were actually doing, haha. Thanks again!
