### ISSUE TITLE
Non - WGS84 CRS unsupported?

### ISSUE THREAD

**Issue by correndo** [Reading-eScience-Centre/ncwms#37]
Hi,
 I've tried to map a netcdf dataset which records ice type classifications over the arctic ocean and the dataset uses a non WGS84 CRS. In the metadata I can see that the grid used is: +proj=stere +a=6378273 +b=6356889.44891 +lat_0=90 +lat_ts=70 +lon_0=-45 

 There is no EPSG code but I believe it is EPSG:3413.

 I added the EPSG codes for the arctic regions but when I try to visualise it in godiva I cannot see anything.
 Is it a problem of projection or something else entirely?

 Attached is the CDL metadata:
[2018-07-18_data.zip](https://github.com/Reading-eScience-Centre/ncwms/files/2565797/2018-07-18_data.zip)

**Comment by guygriffiths** [comment]
Can you send me a sample NetCDF file?  I'm not sure what you used to generate the CDL data, but it is a slightly unusual format, so I cannot just regenerate NetCDF from it.

**Comment by correndo** [comment]
Sure. Thanks.
I think I exported the CDL using panoplyj...

[2018-06-06_data.zip](https://github.com/Reading-eScience-Centre/ncwms/files/2565980/2018-06-06_data.zip)

**Comment by guygriffiths** [comment]
This issue is with your definition of the `xc` and `yc` coordinate variables.  For some reason (I'm still not quite sure what exactly), ncWMS is trying to use them as standard coordinate variables, instead of doing up lookup on your `lon` and `lat` variables.  Removing all attributes from `xc` and `yc` apart from `axis` fixes the issue though.

**Comment by correndo** [comment]
Yay.. it works.. 
I don't understand it either, but it does. Now I have only to figure out how to remove those attributes via api.
Thanks
